// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoDBAtlasDatabaseUser) DeepCopyInto(out *MongoDBAtlasDatabaseUser) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDBAtlasDatabaseUser.
func (in *MongoDBAtlasDatabaseUser) DeepCopy() *MongoDBAtlasDatabaseUser {
	if in == nil {
		return nil
	}
	out := new(MongoDBAtlasDatabaseUser)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MongoDBAtlasDatabaseUser) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoDBAtlasDatabaseUserList) DeepCopyInto(out *MongoDBAtlasDatabaseUserList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MongoDBAtlasDatabaseUser, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDBAtlasDatabaseUserList.
func (in *MongoDBAtlasDatabaseUserList) DeepCopy() *MongoDBAtlasDatabaseUserList {
	if in == nil {
		return nil
	}
	out := new(MongoDBAtlasDatabaseUserList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MongoDBAtlasDatabaseUserList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoDBAtlasDatabaseUserRequestBody) DeepCopyInto(out *MongoDBAtlasDatabaseUserRequestBody) {
	*out = *in
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make([]Role, len(*in))
		copy(*out, *in)
	}
	if in.Scopes != nil {
		in, out := &in.Scopes, &out.Scopes
		*out = make([]Scope, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDBAtlasDatabaseUserRequestBody.
func (in *MongoDBAtlasDatabaseUserRequestBody) DeepCopy() *MongoDBAtlasDatabaseUserRequestBody {
	if in == nil {
		return nil
	}
	out := new(MongoDBAtlasDatabaseUserRequestBody)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoDBAtlasDatabaseUserSpec) DeepCopyInto(out *MongoDBAtlasDatabaseUserSpec) {
	*out = *in
	in.MongoDBAtlasDatabaseUserRequestBody.DeepCopyInto(&out.MongoDBAtlasDatabaseUserRequestBody)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDBAtlasDatabaseUserSpec.
func (in *MongoDBAtlasDatabaseUserSpec) DeepCopy() *MongoDBAtlasDatabaseUserSpec {
	if in == nil {
		return nil
	}
	out := new(MongoDBAtlasDatabaseUserSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoDBAtlasDatabaseUserStatus) DeepCopyInto(out *MongoDBAtlasDatabaseUserStatus) {
	*out = *in
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make([]Role, len(*in))
		copy(*out, *in)
	}
	if in.Scopes != nil {
		in, out := &in.Scopes, &out.Scopes
		*out = make([]Scope, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDBAtlasDatabaseUserStatus.
func (in *MongoDBAtlasDatabaseUserStatus) DeepCopy() *MongoDBAtlasDatabaseUserStatus {
	if in == nil {
		return nil
	}
	out := new(MongoDBAtlasDatabaseUserStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Role) DeepCopyInto(out *Role) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Role.
func (in *Role) DeepCopy() *Role {
	if in == nil {
		return nil
	}
	out := new(Role)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Scope) DeepCopyInto(out *Scope) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Scope.
func (in *Scope) DeepCopy() *Scope {
	if in == nil {
		return nil
	}
	out := new(Scope)
	in.DeepCopyInto(out)
	return out
}
